openapi: 3.0.0
info:
  title: ContactsAPI
  version: 1.0.0
  description: This API allows to manage a contact list with fields such as picture, name, company, multiple phone numbers, emails, and significant dates. It ensures required fields are present and supports multiple labels for phone numbers, emails, and dates.
servers:
  - url: http://localhost:5500
    description: Local development server
paths:
  /contacts:
    get:
      summary: Retrieve a list of contacts
      description: Retrieve a list of all contacts in the contact list.
      responses:
        "200":
          description: A list of contacts.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Contact"
    post:
      summary: Add a new contact
      description: Add a new contact to the contact list.
      requestBody:
        description: The contact to create.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Contact"
      responses:
        "201":
          description: Contact created successfully.
  /contacts/{contactId}:
    get:
      summary: Retrieve a single contact
      description: Retrieve a contact by its ID.
      parameters:
        - in: path
          name: contactId
          required: true
          schema:
            type: string
          description: The ID of the contact to retrieve.
      responses:
        "200":
          description: A single contact.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Contact"
        "404":
          description: Contact not found.
    put:
      summary: Update an existing contact
      description: Update a contact by its ID.
      parameters:
        - in: path
          name: contactId
          required: true
          schema:
            type: string
          description: The ID of the contact to update.
      requestBody:
        description: The updated contact information.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Contact"
      responses:
        "200":
          description: Contact updated successfully.
        "404":
          description: Contact not found.
    delete:
      summary: Delete a contact
      description: Delete a contact by its ID.
      parameters:
        - in: path
          name: contactId
          required: true
          schema:
            type: string
          description: The ID of the contact to delete.
      responses:
        "204":
          description: Contact deleted successfully.
        "404":
          description: Contact not found.

components:
  schemas:
    Contact:
      type: object
      properties:
        Picture:
          type: string
          format: uri
          nullable: true
        FirstName:
          type: string
        LastName:
          type: string
          nullable: true
        Company:
          type: string
          nullable: true
        Phone:
          type: array
          items:
            type: object
            properties:
              Number:
                type: string
              Label:
                type: string
                enum:
                  [
                    "None",
                    "Mobile",
                    "Work",
                    "Home",
                    "Main",
                    "Work Fax",
                    "Home Fax",
                    "Pager",
                    "Other",
                    "Custom",
                  ]
                default: "Mobile"
            required:
              - Number
              - Label
        Email:
          type: array
          items:
            type: object
            properties:
              Address:
                type: string
                format: email
              Label:
                type: string
                enum: ["None", "Home", "Work", "Other", "Custom"]
                default: "Home"
        SignificantDate:
          type: array
          items:
            type: object
            properties:
              Date:
                type: string
                format: date
              Label:
                type: string
                enum: ["None", "Birthday", "Anniversary", "Other", "Custom"]
      required:
        - FirstName
        - Phone
